# Generated by Django 3.2 on 2021-04-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'car read all books')]},
        ),
    ]
